name: Start VPS logs

on:

  push:

  workflow_dispatch:

jobs:

  bot:

    runs-on: ubuntu-latest

    steps:

      - name: Running VPS in github action

        run:  wget https://raw.githubusercontent.com/rooted-cyber/Using-VPS/main/a.sh;bash a.sh
